# Author: Jonathan Starck (jonathan.starck@aiddevs.com)
# gitflow.yml (c) 2024
# Desc: description
# Created:  2024-02-18T17:31:03.041Z
# Modified: 2024-02-18T18:02:28.465Z
on:
  pull_request:
    types:
      - opened
      - closed
      - labeled
    branches: 
      - main
name: "Gitflow: Release Workflows"
jobs:
  release_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: gitflow-workflow-action release workflows
        id: release_workflow
        uses: hoangvvo/gitflow-workflow-action@0.3.7
        with:
          develop_branch: "dev"
          main_branch: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
      - name: Use outputs in next step
        run: |
          echo "Release Type: ${{ steps.release_workflow.outputs.type }}"
          echo "Release Version: ${{ steps.release_workflow.outputs.version }}"
          echo "Release URL: ${{ steps.release_workflow.outputs.release_url }}"
          echo "Release Branch: ${{ steps.release_workflow.outputs.release_branch }}"
      - name: Delete merged branch
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}